from typing import Protocol, Optional
from ..models.order import Order
from ..value_objects.order_status import OrderStatus

class OrderRepository(Protocol):
    async def create(self, order: Order) -> Order: ...
    async def get_by_id(self, order_id: str) -> Optional[Order]: ...
    async def update_status(self, order_id: str, status: OrderStatus) -> Order: ...