version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: order-processing-service:latest
    container_name: order-processing-service
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: orders_db
      MONGO_USER: root
      MONGO_PASSWORD: secret
      MONGO_AUTH_SOURCE: admin
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:7
    container_name: order-processing-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "mongodb://root:secret@127.0.0.1:27017/admin",
        "--quiet",
        "--eval",
        "db.runCommand({ ping: 1 })"
      ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
